### ISSUE TITLE
Raspberry Pi 4

### ISSUE THREAD

**Issue by fabiencomte** [radiolondra/YAMP2#3]
Hello,
Could you explain how do you managed to run on a Raspberry Pi please ?
Is that compatible with .Net Core 7 ?

**Comment by fabiencomte** [comment]
I have this error with Pi 4 and Raspbian 64 bits:
dotnet YAMP2.dll
Unhandled exception. System.InvalidOperationException: Using libvlcDirectoryPath is not supported on the Linux platform. The recommended way is to have the libvlc librairies in /usr/lib. Use LD_LIBRARY_PATH if you need more customization
   at LibVLCSharp.Shared.Core.InitializeDesktop(String libvlcDirectoryPath)
   at LibVLCSharp.Shared.Core.Initialize(String libvlcDirectoryPath)

**Comment by radiolondra** [comment]
> Could you explain how do you managed to run on a Raspberry Pi please ?

Hi Fabien, I never said YAMP2 runs on Raspberry Pi, at least I never tested it. Anyway, I suggest you to start with something simpler with Raspberry (https://github.com/AvaloniaUI/Avalonia/issues/2571#issuecomment-1088445345) and then,once the simple sample works, try with YAMP2.

> Is that compatible with .Net Core 7 ?

Same answer.

**Comment by fabiencomte** [comment]
Hello,
Your "This unofficial distribution of the library has been tested with full success in Windows, Linux, MacOS and Raspberry Pi 3 (1GB RAM) with DietPi as operating system." make me thinked that it was ok on raspberry pi, my mistake.
Thank you for your response.
